site_name: HealthAI Web Platform Documentation
site_description: Documentation for the HealthAI Web Platform

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue

nav:
  - Home: index.md
  - Models:
    - scVI Model: models/scvi.md
  - Contribution Guide: contribution.md
  # Temporarily comment out missing files
  # - Getting Started: getting-started.md
  # - Developer Guide: developer-guide.md
  # - API Reference: api-reference.md

plugins:
  - search

markdown_extensions:
  - codehilite
  - toc:
      permalink: true 